/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CardSubjectIdImport } from './routes/card.$subjectId'

// Create Virtual Routes

const TestComponentLazyImport = createFileRoute('/test-component')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TestComponentLazyRoute = TestComponentLazyImport.update({
  path: '/test-component',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/test-component.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CardSubjectIdRoute = CardSubjectIdImport.update({
  path: '/card/$subjectId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/test-component': {
      preLoaderRoute: typeof TestComponentLazyImport
      parentRoute: typeof rootRoute
    }
    '/card/$subjectId': {
      preLoaderRoute: typeof CardSubjectIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  TestComponentLazyRoute,
  CardSubjectIdRoute,
])

/* prettier-ignore-end */
